### ISSUE TITLE
lake update failed

### ISSUE THREAD

**Issue by dannypsnl** [Paper-Proof/paperproof#28]
The output of command `lake update`

```
error: > git rev-parse --verify HEAD    # in directory ./lake-packages/Paperproof
error: stderr:
fatal: Needed a single revision
error: external command `git` exited with code 128
```

1. Lean (version 4.1.0, commit a832f398b80a, Release)
2. git version 2.42.0

**Comment by lakesare** [comment]
Can't reproduce, both `lake update Paperproof` and just `lake update` run fine for me.

Could you describe the steps you took, did it happen during the #Installation https://github.com/Paper-Proof/paperproof#installation process?

Does clearing your cache (`lake clean; lake exe cache clean!`) and reinstalling Paperproof help?

**Comment by dannypsnl** [comment]
In the end, I solve this by

```shell
rm -rf lake-packages/Paperproof/
```

I'm not sure how it run into the problem, either.
