### ISSUE TITLE
How can I suppress "parseTree XXXms" output?

### ISSUE THREAD

**Issue by minaph** [Paper-Proof/paperproof#40]
I have always used the VS Code extension. I like it very much. But the frequent appearance of notifications like parseTree XXXms is a bit depressing. Is there any way to turn it off?

**Comment by lakesare** [comment]
Oops, thanks for telling us!
Removed these notifications, please update paperproof with `lake update Paperproof`.

**Comment by minaph** [comment]
Thank you!!
