### ISSUE TITLE
Can't see the paperproof render on Linux

### ISSUE THREAD

**Issue by patrik-cihal** [Paper-Proof/paperproof#43]
I am using Linux. I can see the Lean Infoview however when I click the Paperproof window, there is nothing. 

I've followed the tutorial: 1. Installed extension 2. Required paperproof 3. Imported paperproof 4. Used "lake update" and made sure my lean version is up to date

![pic-selected-240530-1611-35](https://github.com/Paper-Proof/paperproof/assets/103130191/86583735-d238-41e4-b3b2-abd5e3db3ce3)

**Comment by lakesare** [comment]
We had this issue very recently (https://github.com/Paper-Proof/paperproof/issues/41).

It can stem either from the incompatibility of Paperproof with your `Lean` version, or from  incompatibility of Paperproof with your `vscode-lean extension` version.

Latest Paperproof should work with all `Lean` and `vscode-lean extension` versions, however, - so if you're on the latest Paperproof version, and you still get a blank page, I will look into it again.

Some questions:
1. Does it get fixed when you fully close vscode, and fully open it again?
2. What are your:
     - `lean-vscode extension` version
     - `Lean` version
     - `Paperproof extension` version
     - `Paperproof lean library` version

**Comment by patrik-cihal** [comment]
Lean version 4.8.0-rc2
Lean4 vscode extension version: 0.0.155 (more info in picture)
Paperproof extension version: v1.3.0
Paperproof lean library version: Don't know how to find that

![pic-selected-240601-1127-46](https://github.com/Paper-Proof/paperproof/assets/103130191/d8365928-1cdd-4d94-b02d-baba68cb56d8)

**Comment by patrik-cihal** [comment]
And no it doesn't get fixed even after fully closing vscode.

**Comment by lakesare** [comment]
Thanks for the details! I can reproduce this with `Lean4 vscode extension version: 0.0.155`, `lean-vscode` updated its api again.

A temporary solution is to downgrade `lean-vscode` to version `0.0.144`, then fully close and open the vscode window. 

Added this step to the readme ([link](https://github.com/Paper-Proof/paperproof?tab=readme-ov-file#installation)).

___

Thank you for the report, please reopen the issue if downgrading `lean-vscode` doesn't work for you.
